### ISSUE TITLE
hl not working in git merge

### ISSUE THREAD

**Issue by towry** [daschw/leaf.nvim#10]
When using nvim as git merge tool.

leaf:

<img width="1590" alt="截屏2023-12-07 11 06 03" src="https://github.com/daschw/leaf.nvim/assets/8279858/9fb071fc-f5a4-4ba2-895d-c585b3b0281a">

default colorscheme(nightly):
<img width="811" alt="截屏2023-12-07 11 06 10" src="https://github.com/daschw/leaf.nvim/assets/8279858/f14d0df9-b241-4267-ad7d-19140d5053dd">

**Comment by towry** [comment]
https://github.com/daschw/leaf.nvim/blob/f54d87774887628264fe8fe6b8beb7b4af9ffd98/lua/leaf/hlgroups.lua#L22

I deem it's because this `bg` is same with normal `bg`, I can contribute to this once I got time.

**Comment by daschw** [comment]
Thanks a lot for reporting! I guess I'll have to rework the Diff highlights. I'll look into this soon.

**Comment by daschw** [comment]
I hope this is fixed by https://github.com/daschw/leaf.nvim/commit/ce8964e575e35cbcfc9ccd0f60fd1306315d210a 
With my setup
```bash
git difftool --tool vimdiff
```
now looks like this
![swappy-20231208_191034](https://github.com/daschw/leaf.nvim/assets/16589944/14ec1387-2ab5-4a98-92f3-d28cc704493d)

Let me know if you'd prefer different styling.

**Comment by towry** [comment]
Just tested it on repo with conflicts, looks great, thanks!
